#  Unit 2.4a Using Programs with Data, SQLAlchemy
> Using Programs with Data is focused on SQL and database actions.  Part A focuses on SQLAlchemy and an OOP programming style,
- toc: true
- image: /images/python.png
- categories: []
- type: ap
- week: 26

# Database and SQLAlchemy
> In this blog we will explore using programs with data, focused on Databases.  We will use SQLite Database to learn more about using Programs with Data.  ***Use Debugging through these examples to examine Objects created in Code***.

- College Board talks about ideas like 
    - Program Usage. "iterative and interactive way when processing information"
    - Managing Data.  "classifying data are part of the process in using programs", "data files in a Table"
    - Insight "insight and knowledge can be obtained from ...  digitally represented information"
    - Filter systems. 'tools for finding information and recognizing patterns"
    - Application. "the preserve has two databases", "an employee wants to count the number of book"

- PBL, Databases, Iterative/OOP
    - Iterative. Refers to a sequence of instructions or code being repeated until a specific end result is achieved
    - OOP. A computer programming model that organizes software design around data, or objects, rather than functions and logic
    - SQL. Structured Query Language, abbreviated as SQL, is a language used in programming, managing, and structuring data

## Imports and Flask Objects
> Defines and key object creations

- Comment on where you have observed these working?  Provide a defintion of purpose.
    1. Flask app object
    2. SQLAlchemy db object

In [2]:
"""
These imports define the key objects
"""

from flask import Flask
from flask_sqlalchemy import SQLAlchemy

"""
These object and definitions are used throughout the Jupyter Notebook.
"""

# Setup of key Flask object (app)
app = Flask(__name__)
# Setup SQLAlchemy object and properties for the database (db)
database = 'sqlite:///sqlite.db'  # path and filename of database
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config['SQLALCHEMY_DATABASE_URI'] = database
app.config['SECRET_KEY'] = 'SECRET_KEY'
db = SQLAlchemy()


# This belongs in place where it runs once per project
db.init_app(app)

## Model Definition
> Define columns, initialization, and CRUD methods for users table in sqlite.db

- Comment on these items in the class, purpose and defintion.
    - class User
    - db.Model inheritance
    - _init_ method
    - ```@property```, ```@<column>.setter```
    - create, read, update, delete methods

In [3]:
""" database dependencies to support sqlite examples """
import datetime 
from datetime import datetime
import json

from sqlalchemy.exc import IntegrityError
from werkzeug.security import generate_password_hash, check_password_hash


''' Tutorial: https://www.sqlalchemy.org/library.html#tutorials, try to get into a Python shell and follow along '''

# Define the User class to manage actions in the 'users' table
# -- Object Relational Mapping (ORM) is the key concept of SQLAlchemy
# -- a.) db.Model is like an inner layer of the onion in ORM
# -- b.) User represents data we want to store, something that is built on db.Model
# -- c.) SQLAlchemy ORM is layer on top of SQLAlchemy Core, then SQLAlchemy engine, SQL
# defining the template the class of Users, class definition template, helps us create objects which are of the type User, template for future object
class Restaurant_B(db.Model):
    __tablename__ = 'Restaurant_business'  # table name is plural, class name is singular

    # Define the User schema with "vars" from object
    id = db.Column(db.Integer, primary_key=True)
    _Restaurant = db.Column(db.String(255), unique=True, nullable=False)
    _Sales = db.Column(db.String(255), unique=False, nullable=False)
    _Avg = db.Column(db.String(255), unique=False, nullable=False)
    _City = db.Column(db.String(255), unique=False, nullable=False)
    _State = db.Column(db.String(255), unique=False, nullable=False)
    _Meals = db.Column(db.String, unique=False)

    # constructor of a User object, initializes the instance variables within object (self)
    def __init__(self, Restaurant, Sales, Avg, City, State, Meals):
        self._Restaurant = Restaurant    # variables with self prefix become part of the object, 
        self._Sales = Sales
        self._Avg = Avg
        self._City = City
        self._State = State
        self._Meals = Meals

    # a name getter method, extracts name from object
    @property
    def Restaurant(self):
        return self._Restaurant
    
    # a setter function, allows name to be updated after initial object creation
    @Restaurant.setter
    def Restaurant(self, Restaurant):
        self._Restaurant = Restaurant
    
    @property
    def Sales(self):
        return self._Sales
    
    # a setter function, allows name to be updated after initial object creation
    @Sales.setter
    def Sales(self, Sales):
        self._Sales = Sales

    @property
    def Avg(self):
        return self._Avg
    
    # a setter function, allows name to be updated after initial object creation
    @Avg.setter
    def Avg(self, Avg):
        self._Avg = Avg

    @property
    def City(self):
        return self._City
    
    # a setter function, allows name to be updated after initial object creation
    @City.setter
    def City(self, City):
        self._City = City

    @property
    def State(self):
        return self._State
    
    # a setter function, allows name to be updated after initial object creation
    @State.setter
    def State(self, State):
        self._State = State

    @property
    def Meals(self):
        return self._Meals
    
    @Meals.setter
    def Meals(self, Meals):
        self._Meals = Meals
    
    # output content using str(object) in human readable form, uses getter
    # output content using json dumps, this is ready for API response
    def __str__(self):
        return json.dumps(self.read())

    # CRUD create/add a new record to the table
    # returns self or None on error
    def create(self):
        try:
            # creates a person object from User(db.Model) class, passes initializers
            db.session.add(self)  # add prepares to persist person object to Users table
            db.session.commit()  # SqlAlchemy "unit of work pattern" requires a manual commit
            return self
        except IntegrityError:
            db.session.remove()
            return None

    # CRUD read converts self to dictionary
    # returns dictionary
    def read(self):
        return {
            "id": self.id,
            "Restaurant" : self.Restaurant,
            "Sales" : self.Sales,
            "Avg" : self.Avg,
            "City" : self.City,
            "State": self.State,
            "Meals": self.Meals
        }

    # CRUD update: updates user name, password, phone
    # returns self
    def update(self, Restaurant, Sales, Avg, City, State, Meals):
        """only updates values with length"""
        if len(Restaurant) > 0:
            self.Restaurant = Restaurant
        if len(Sales) > 0:
            self.Sales = Sales
        if len(Avg) > 0:
            self.Avg = Avg
        if len(City) > 0:
            self.City = City
        if len(State) > 0:
            self.State = State
        if len(Meals) > 0:
            self.Meals = Meals
        db.session.add(self)
        db.session.commit()
        return self

    # CRUD delete: remove self
    # None
    def delete(self):
        db.session.delete(self)
        db.session.commit()
        return None

## Initial Data
> Uses SQLALchemy db.create_all() to initialize rows into sqlite.db

- Comment on how these work?
    1. Create All Tables from db Object
    2. User Object Constructors
    3. Try / Except

In [4]:

# Builds working data for testing
def initRestaurant_business():
    with app.app_context():
        """Create database and tables"""
        db.create_all()
        """Tester data for table"""
        R1 = Restaurant_B(Restaurant='Komodo', Sales='41,000,000', Avg='115', City='Miami', State='Fla.', Meals='285,000')
        R2 = Restaurant_B(Restaurant='The Boathouse Orlando', Sales='39,863,628', Avg='44', City='Fla.', State='25', Meals='921,785')
        R3 = Restaurant_B(Restaurant='Swan', Sales='31,000,000', Avg='85', City='Miami',State='Fla.', Meals='185,000')
        R4 = Restaurant_B(Restaurant='Maple & Ash (Chicago)', Sales='30,286,684', Avg='106', City='Chicago', State='Ill.', Meals='285,714')
        R5 = Restaurant_B(Restaurant='Mila', Sales='27,350,000', Avg='134', City='Miami Beach', State='Fla.', Meals='203,990')
        R6 = Restaurant_B(Restaurant='Alinea', Sales='27,072,500', Avg='650', City='Chicago', State='Ill.', Meals='41,650')
        R7 = Restaurant_B(Restaurant='CTop of the World', Sales='25,672,308', Avg='133', City='Las Vegas', State='Nev.', Meals='218,586')
        R8 = Restaurant_B(Restaurant='Shooters Waterfront', Sales='25,025,370', Avg='68', City='Fort Lauderdale', State='Fla.', Meals='419,972')
        R9 = Restaurant_B(Restaurant='Prime 112', Sales='24,750,000', Avg='155', City='Miami Beach', State='Fla.', Meals='210,000')
        R10 = Restaurant_B(Restaurant='Paddlefish', Sales='23,795,000', Avg='52', City='Orlando', State='Fla.', Meals='485,000')
        R11 = Restaurant_B(Restaurant='Capa', Sales='23,547,000', Avg='121', City='Orlando', State='Fla.', Meals='197,000')
        R12 = Restaurant_B(Restaurant='Maple & Ash (Scottsdale)', Sales='23,487,122', Avg='95', City='Scottsdale', State='Ariz.', Meals='247,232')
        R13 = Restaurant_B(Restaurant='Commanders Palace', Sales='23,184,000', Avg='89', City='New Orleans', State='La.', Meals='264,000' )
        R14 = Restaurant_B(Restaurant='Taste of Texas', Sales='23,180,522', Avg='64', City='Houston', State='Texas', Meals='356,894')
        R15 = Restaurant_B(Restaurant='Joes Seafood, Prime Steak & Stone Crab', Sales='22,477,000', Avg='94', City='Washington', State='N/A', Meals='255,000')
        Rest = [R1, R2, R3, R4, R5, R6, R7, R8, R9, R10, R11, R12, R13, R14, R15]
        for R in Rest:
            try:
                object = R.create()
                print(f"Added data for {object.Restaurant}")
            except IntegrityError:
                '''fails with bad or duplicate data'''
                print(f"Records exist, duplicate email, or error: {R.Restaurant}") 

initRestaurant_business()

Added data for Komodo
Added data for The Boathouse Orlando
Added data for Swan
Added data for Maple & Ash (Chicago)
Added data for Mila
Added data for Alinea
Added data for CTop of the World
Added data for Shooters Waterfront
Added data for Prime 112
Added data for Paddlefish
Added data for Capa
Added data for Maple & Ash (Scottsdale)
Added data for Commanders Palace
Added data for Taste of Texas
Added data for Joes Seafood, Prime Steak & Stone Crab

## Check for given Credentials in users table in sqlite.db
> Use of ORM Query object and custom methods to identify user to credentials uid and password

- Comment on purpose of following
    1. User.query.filter_by
    2. user.password

In [5]:
def find_by_Restaurant(Restaurant):
    with app.app_context():
        # ORM allows us to do query methods on our data
        # only returns the match to the first match to the database
        restaurant_B = Restaurant_B.query.filter_by(_Restaurant=Restaurant).first()
    return restaurant_B # returns user object

## Create a new User in table in Sqlite.db
> Uses SQLALchemy and custom user.create() method to add row.

- Comment on purpose of following
    1. user.find_by_uid() and try/except
    2. user = User(...)
    3. user.dob and try/except
    4. user.create() and try/except

In [6]:
def create():
    # optimize user time to see if uid exists
    Restaurant = input("Enter a Restaurant name:")
    Dinner = find_by_Restaurant(Restaurant)
    try:
        print("Found\n", Dinner.read())
        return
    except:
        pass # keep going
    
    # request value that ensure creating valid object
    Sales = input("Enter the total sales:")
    Avg = input("Enter their average check:")
    City = input("Enter the City:")
    State = input("Enter the state:")
    Meals = input("Enter the total meals served:")

    # Initialize User object before date
    restaurant_B = Restaurant_B(Restaurant=Restaurant, 
                Sales=Sales, 
                Avg=Avg,
                City=City,
                State=State,
                Meals=Meals
                )
           
    # write object to database
    with app.app_context():
        try:
            object = restaurant_B.create()
            print("Created\n", object.read())
        except:  # error raised if object not created
            print("Unknown error uid {Restaurant}")
        
create()

Created
 {'id': 16, 'Restaurant': 'Habit Burger Grill', 'Sales': '5', 'Avg': '3', 'City': 'san diego', 'State': 'california', 'Meals': '70'}

## Reading users table in sqlite.db
> Uses SQLALchemy query.all method to read data

- Comment on purpose of following
    1. User.query.all
    2. json_ready assignment, google List Comprehension

In [19]:
def read():
    with app.app_context():
        table = Restaurant_B.query.all()
    json_ready = [restaurant_B.read() for restaurant_B in table] # "List Comprehensions", for each user add user.read() to list
    return json_ready

read()

[{'id': 2,
  'Restaurant': 'The Boathouse Orlando',
  'Sales': '39,863,628',
  'Avg': '44',
  'City': 'Fla.',
  'State': '25',
  'Meals': '921,785'},
 {'id': 3,
  'Restaurant': 'Swan',
  'Sales': '31,000,000',
  'Avg': '85',
  'City': 'Miami',
  'State': 'Fla.',
  'Meals': '185,000'},
 {'id': 4,
  'Restaurant': 'Maple & Ash (Chicago)',
  'Sales': '30,286,684',
  'Avg': '106',
  'City': 'Chicago',
  'State': 'Ill.',
  'Meals': '285,714'},
 {'id': 5,
  'Restaurant': 'Mila',
  'Sales': '27,350,000',
  'Avg': '134',
  'City': 'Miami Beach',
  'State': 'Fla.',
  'Meals': '203,990'},
 {'id': 6,
  'Restaurant': 'Alinea',
  'Sales': '27,072,500',
  'Avg': '650',
  'City': 'Chicago',
  'State': 'Ill.',
  'Meals': '41,650'},
 {'id': 7,
  'Restaurant': 'CTop of the World',
  'Sales': '25,672,308',
  'Avg': '133',
  'City': 'Las Vegas',
  'State': 'Nev.',
  'Meals': '218,586'},
 {'id': 8,
  'Restaurant': 'Shooters Waterfront',
  'Sales': '25,025,370',
  'Avg': '68',
  'City': 'Fort Lauderdale',
  'State': 'Fla.',
  'Meals': '419,972'},
 {'id': 9,
  'Restaurant': 'Prime 112',
  'Sales': '24,750,000',
  'Avg': '155',
  'City': 'Miami Beach',
  'State': 'Fla.',
  'Meals': '210,000'},
 {'id': 10,
  'Restaurant': 'Paddlefish',
  'Sales': '23,795,000',
  'Avg': '52',
  'City': 'Orlando',
  'State': 'Fla.',
  'Meals': '485,000'},
 {'id': 11,
  'Restaurant': 'Capa',
  'Sales': '23,547,000',
  'Avg': '121',
  'City': 'Orlando',
  'State': 'Fla.',
  'Meals': '197,000'},
 {'id': 12,
  'Restaurant': 'Maple & Ash (Scottsdale)',
  'Sales': '23,487,122',
  'Avg': '95',
  'City': 'Scottsdale',
  'State': 'Ariz.',
  'Meals': '247,232'},
 {'id': 13,
  'Restaurant': 'Commanders Palace',
  'Sales': '23,184,000',
  'Avg': '89',
  'City': 'New Orleans',
  'State': 'La.',
  'Meals': '264,000'},
 {'id': 14,
  'Restaurant': 'Taste of Texas',
  'Sales': '23,180,522',
  'Avg': '64',
  'City': 'Houston',
  'State': 'Texas',
  'Meals': '356,894'},
 {'id': 15,
  'Restaurant': 'Joes Seafood, Prime Steak & Stone Crab',
  'Sales': '22,477,000',
  'Avg': '94',
  'City': 'Washington',
  'State': 'N/A',
  'Meals': '255,000'},
 {'id': 16,
  'Restaurant': 'Habit Burger Grill',
  'Sales': '20,000',
  'Avg': '50',
  'City': 'San Diego',
  'State': 'Ca',
  'Meals': '50,000'},
 {'id': 17,
  'Restaurant': 'Komodo',
  'Sales': '50,000',
  'Avg': '50',
  'City': 'miami',
  'State': 'fa.',
  'Meals': '500'}]

# Hacks
- Add this Blog to you own Blogging site.  In the Blog add notes and observations on each code cell.
- Change blog to your own database.
- Add additional CRUD
    - Add Update functionality to this blog.
    - Add Delete functionality to this blog.

In [14]:
def updateq():    
    Restaurant = input("Enter the name of the Restaurant to update: ")
    Dinner = find_by_Restaurant(Restaurant)
    
    # Request new values for the QB attributes
    Sales = input("Enter their Total Sales : ")
    Avg = input("Enter their Average Checks : ")
    City = input("Enter their City season: ")
    State = input("Enter Their state: ")
    Meals = input("Enter their total Meals: ")
    
    if Dinner is not None:
        with app.app_context():
            Dinner.update(Restaurant=Restaurant, Sales=Sales, Avg=Avg, City=City, State=State, Meals=Meals)
            print("Updated Restaurant", Restaurant)
    else:
        print("error")

updateq()

Updated Restaurant Komodo

In [16]:
def delete():
    # optimize user time to see if uid exists
    Restaurant = input("Enter a Restaurant name:")
    Dinner = find_by_Restaurant(Restaurant)
    try:
        pass
    except:
        Restaurant = input("Try again, that was not a valid Restaurant:")
    
    with app.app_context():
        try:
            object = Dinner.delete()
            print("Deleted\n", Dinner)
        except:  # error raised if object not created
            print("Unknown error uid {Restaurant}")
delete()

Deleted
 {"id": 1, "Restaurant": "Komodo", "Sales": "80,000", "Avg": "500", "City": "Miami", "State": "Fa.", "Meals": "50"}

In [18]:
def crudmenu():
    selection = input("Enter a letter to select your option --> c: Create, r: Read, u: Update, d: delete")
    if selection.lower() == "c":
        create()
    elif selection.lower() == "r":
        with app.app_context():
            table = Restaurant_B.query.all()
        json_ready = [restaurant_B.read() for restaurant_B in table]
        return json_ready
    elif selection.lower() == "u":
        updateq()
    elif selection.lower() == "d":
        delete()
    else:
        selection = input("Please enter a valid letter --> c: Create, r: Read, u: Update, D: delete")

crudmenu()

Created
 {'id': 17, 'Restaurant': 'Komodo', 'Sales': '50,000', 'Avg': '50', 'City': 'miami', 'State': 'fa.', 'Meals': '500'}